name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23lif8xfdSSzxgkWgi"
GITHUB_OWNER = "RunWang925"
GITHUB_REPO = "NavSphere-Run"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere-run1-dwk9njqs.edgeone.run/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere-run1-dwk9njqs.edgeone.run"
